import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@mui/material";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, session,
}: any
 ) {
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Container maxWidth="lg">{children}</Container>
        </SessionProvider>
      </body>
    </html>
  );
}
